" Example Vim graphical configuration.
" Copy to ~/.gvimrc or ~/_gvimrc.

set guifont=Monaco:h18
let g:solarized_style     =   "dark"
let g:solarized_contrast  =   "high"
" 
set antialias                     " MacVim: smooth fonts.
set encoding=utf-8                " Use UTF-8 everywhere.
set guioptions-=T                 " Hide toolbar.
set background=dark              " Background.
set lines=25 columns=100          " Window dimensions.
colorscheme solarized

set guioptions-=r                 " Don't show right scrollbar


